"""Declarative base and the column mixins every table is built from."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Constraints and indexes are named by rule, not by whatever Postgres picks. A later
# migration has to name what it drops, and `users_email_key` is not something anyone
# should have to look up.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base for every ORM model. `Base.metadata` is what Alembic compares against."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPk:
    """A `uuid` primary key generated by Postgres, not by the application."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` / `updated_at`, both server-side.

    `updated_at` is maintained by the `set_updated_at()` trigger installed in the initial
    migration. Application code never writes it — a trigger cannot be forgotten by a
    repository function, and a repository function can.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
